#include <stdio.h>
#include <string.h>
int  main ()
{
    int i,len,count=0;
    int  a1=0, b1=0, c1=0, d1=0, e1=0, f1=0, g1=0, h1=0, i1=0, j1=0, k1=0, l1=0,  m1=0, n1=0, o1=0, p1=0, q1=0, r1=0, s1=0, t1=0, u1=0, v1=0, w1=0, x1=0, y1=0, z1=0;
    char s[100];
    scanf("%s",&s);
    len=strlen(s);
    for(i=0;i<len;i++)
    {
        if(s[i]=='a')
        {
            if(a1<1)
                a1++;
            else
                continue;
        }
         if(s[i]=='b')
        {
            if(b1<1)
                b1++;
            else
                continue;
        }
         if(s[i]=='c')
        {
            if(c1<1)
                c1++;
            else
                continue;
        }
         if(s[i]=='d')
        {
            if(d1<1)
                d1++;
            else
                continue;
        }
         if(s[i]=='e')
        {
            if(e1<1)
                e1++;
            else
                continue;
        }
         if(s[i]=='f')
        {
            if(f1<1)
                f1++;
            else
                continue;
        }
         if(s[i]=='g')
        {
            if(g1<1)
                g1++;
            else
                continue;
        }
         if(s[i]=='h')
        {
            if(h1<1)
                h1++;
            else
                continue;
        }
         if(s[i]=='i')
        {
            if(i1<1)
                i1++;
            else
                continue;
        }
         if(s[i]=='j')
        {
            if(j1<1)
                j1++;
            else
                continue;
        }
         if(s[i]=='k')
        {
            if(k1<1)
                k1++;
            else
                continue;
        }
         if(s[i]=='l')
        {
            if(l1<1)
                l1++;
            else
                continue;
        }
         if(s[i]=='m')
        {
            if(m1<1)
                m1++;
            else
                continue;
        }
         if(s[i]=='n')
        {
            if(n1<1)
                n1++;
            else
                continue;
        }
         if(s[i]=='o')
        {
            if(o1<1)
                o1++;
            else
                continue;
        }
         if(s[i]=='p')
        {
            if(p1<1)
                p1++;
            else
                continue;
        }
         if(s[i]=='q')
        {
            if(q1<1)
                q1++;
            else
                continue;
        }
         if(s[i]=='r')
        {
            if(r1<1)
                r1++;
            else
                continue;
        }
         if(s[i]=='s')
        {
            if(s1<1)
                s1++;
            else
                continue;
        }
         if(s[i]=='t')
        {
            if(t1<1)
                t1++;
            else
                continue;
        }
         if(s[i]=='u')
        {
            if(u1<1)
                u1++;
            else
                continue;
        }
         if(s[i]=='v')
        {
            if(v1<1)
                v1++;
            else
                continue;
        }
         if(s[i]=='w')
        {
            if(w1<1)
                w1++;
            else
                continue;
        }
         if(s[i]=='x')
        {
            if(x1<1)
                x1++;
            else
                continue;
        }
         if(s[i]=='y')
        {
            if(y1<1)
                y1++;
            else
                continue;
        }
         if(s[i]=='z')
        {
            if(z1<1)
                z1++;
            else
                continue;
        }

    }
    count=a1+b1+c1+d1+e1+f1+g1+h1+i1+j1+k1+l1+m1+n1+o1+p1+q1+r1+s1+t1+u1+v1+w1+x1+y1+z1;

    if(count%2==0)
        printf("CHAT WITH HER!\n");
    else
        printf("IGNORE HIM!\n");
    return 0;
}
